/* ============ WORKOUT DATA ============ */
// Noah — 14 y/o, 5'3" / 100lb, basketball year-round + football fall
// 6-12 mo lifting exp. 4 days × ~45 min. Goals: speed, power, agility,
// build muscle, look better.

const WORKOUTS = {
  A: {
    name: "Upper Strength",
    color: "#C03028",
    focus: "Push / pull strength. Builds the pressing & pulling foundation.",
    duration: 45,
    exercises: [
      { id: "bench",  name: "Barbell Bench Press",         target: "4×5",         sets: 4, unit: "lb",
        cues: ["Spotter required", "Feet planted, shoulder blades pinched", "Bar to mid-chest, drive through feet"],
        search: "barbell bench press form" },
      { id: "pullup", name: "Pull-ups",                    target: "4×5–8",       sets: 4, unit: "reps",
        cues: ["Goal: 10 strict pull-ups by week 8", "Full hang, chin over bar", "Band assist allowed"],
        search: "pull up proper form" },
      { id: "ohp",    name: "Seated DB Overhead Press",    target: "3×8",         sets: 3, unit: "lb",
        cues: ["Seated with back support", "Press straight up, not forward", "Core tight, no arching"],
        search: "seated dumbbell overhead press" },
      { id: "dbrow",  name: "One-Arm DB Row",              target: "3×10 / side", sets: 3, unit: "lb",
        cues: ["Hand and knee on bench", "Pull elbow to hip, not armpit", "Flat back, no twisting"],
        search: "one arm dumbbell row" },
      { id: "ezcurl", name: "EZ-Bar Curl",                 target: "3×10",        sets: 3, unit: "lb",
        cues: ["Elbows pinned at sides", "Control the down phase", "No swinging"],
        search: "ez bar curl form" },
      { id: "plank",  name: "Plank",                       target: "3×40s",       sets: 3, unit: "sec",
        cues: ["Straight line head to heels", "Squeeze glutes, brace core", "No sagging"],
        search: "plank proper form" },
    ],
  },
  B: {
    name: "Lower Strength + Agility",
    color: "#78C850",
    focus: "Squat, hinge, cuts. The basketball/football engine.",
    duration: 50,
    exercises: [
      { id: "5105",     name: "5-10-5 Pro Agility",        target: "4 reps",      sets: 4, unit: "reps",
        cues: ["3 cones, 5 yards apart", "Sprint right 5, left 10, back 5", "Full rest between reps"],
        search: "5-10-5 pro agility shuttle" },
      { id: "lshuffle", name: "Lateral Shuffle",           target: "4 rounds",    sets: 4, unit: "rounds",
        cues: ["Low athletic stance", "Don't cross feet", "Push off outside foot"],
        search: "lateral shuffle drill" },
      { id: "goblet",   name: "Goblet Squat",              target: "4×8",         sets: 4, unit: "lb",
        cues: ["Heaviest DB at chest", "Chest up, elbows inside knees", "Full depth if mobility allows"],
        search: "goblet squat form" },
      { id: "rdl",      name: "Romanian Deadlift",         target: "3×8",         sets: 3, unit: "lb",
        cues: ["Push hips back, slight knee bend", "Bar close to legs, flat back", "Feel hamstrings stretch"],
        search: "romanian deadlift dumbbell" },
      { id: "wlunge",   name: "Walking Lunges (DBs)",      target: "3×8 / leg",   sets: 3, unit: "lb",
        cues: ["Long step, front knee over ankle", "Back knee light tap", "Drive through front heel"],
        search: "walking lunges dumbbell" },
      { id: "calf",     name: "Single-Leg Calf Raise",     target: "3×12 / side", sets: 3, unit: "reps",
        cues: ["Stand on step edge if possible", "Full range — toes up, heel below", "Strong ankles = injury-proof cuts"],
        search: "single leg calf raise" },
    ],
  },
  C: {
    name: "Upper Hypertrophy + Power",
    color: "#F08030",
    focus: "Size work. Fills out the frame + explosive medball power.",
    duration: 45,
    exercises: [
      { id: "slam",    name: "Slam Ball",                  target: "4×6",         sets: 4, unit: "reps",
        cues: ["Full extension overhead first", "Slam hard, fully commit", "Reset and go again"],
        search: "medicine ball slam form" },
      { id: "incline", name: "Incline DB Press",           target: "4×10",        sets: 4, unit: "lb",
        cues: ["Bench at ~30° incline", "DBs just outside shoulders", "Press up and slightly together"],
        search: "incline dumbbell press" },
      { id: "trxrow",  name: "TRX Inverted Row",           target: "4×10–12",     sets: 4, unit: "reps",
        cues: ["Feet forward = harder", "Straight body, squeeze blades", "Chest to hands at top"],
        search: "trx inverted row" },
      { id: "lraise",  name: "DB Lateral Raise",           target: "3×12",        sets: 3, unit: "lb",
        cues: ["Slight elbow bend", "Lead with elbows", "Stop at shoulder height"],
        search: "dumbbell lateral raise" },
      { id: "pushup",  name: "Push-ups on Handles",        target: "3×AMRAP-2",   sets: 3, unit: "reps",
        cues: ["Stop 2 reps shy of failure", "Body straight, elbows ~45°", "Deeper range than floor"],
        search: "push up proper form" },
      { id: "farmer",  name: "Farmer Carry",               target: "3×30s",       sets: 3, unit: "lb",
        cues: ["Heaviest DBs he can hold", "Walk tall, shoulders back", "Grip + traps + core"],
        search: "farmer carry walk" },
    ],
  },
  D: {
    name: "Lower Power + Conditioning",
    color: "#F8D030",
    focus: "Jumping, sprinting, single-leg. Vert + first-step speed.",
    duration: 45,
    exercises: [
      { id: "boxjump",    name: "Box Jump",                target: "4×3",         sets: 4, unit: "reps",
        cues: ["Stable box only", "Land soft, quiet feet", "Step down each rep — don't rebound"],
        search: "box jump form" },
      { id: "broadjump",  name: "Broad Jump",              target: "3×3",         sets: 3, unit: "reps",
        cues: ["Explode horizontally", "Stick the landing — no stumble", "Arms drive forward"],
        search: "broad jump standing" },
      { id: "skater",     name: "Lateral Bound (Skater)",  target: "3×4 / side",  sets: 3, unit: "reps",
        cues: ["Push off outside foot", "Land opposite foot, stick 1 sec", "Basketball D-slide power"],
        search: "skater jump lateral bound" },
      { id: "frontsq",    name: "Front Squat / Goblet",    target: "3×6",         sets: 3, unit: "lb",
        cues: ["Bar / DB on front delts, elbows up", "Torso stays upright", "Switch to front squat at 70+ lb goblet"],
        search: "front squat form" },
      { id: "slrdl",      name: "Single-Leg RDL (DB)",     target: "3×8 / leg",   sets: 3, unit: "lb",
        cues: ["Tall on one leg", "Hinge forward, back leg kicks", "Huge for cuts + jump balance"],
        search: "single leg romanian deadlift" },
      { id: "bss",        name: "Bulgarian Split Squat",   target: "3×8 / leg",   sets: 3, unit: "lb",
        cues: ["Back foot on bench", "Most weight on front leg", "Drop straight down"],
        search: "bulgarian split squat dumbbell" },
      { id: "rowerg",     name: "Row Intervals",           target: "5×250m",      sets: 5, unit: "sec",
        cues: ["Hard effort, not all-out", "1 min rest between", "Off-season: 6×300m"],
        search: "concept 2 rower form" },
    ],
  },
};

const DAY_ORDER = ['A', 'B', 'C', 'D'];

/* ============ PLAN COPY ============ */
const PLAN_COPY = {
  mission: {
    title: "The Mission",
    body: `Build an <b>explosive, durable athlete</b> for basketball year-round and football in fall. 4 days a week, 45 minutes a session. The plan rotates <b>upper/lower</b> and <b>strength/power</b> so nothing gets overtrained — and you still have legs for the court.`
  },
  why: [
    { h: "Why 4 days", p: "Enough volume to actually get stronger. Little enough that you can still hoop, recover, and grow. Miss one — push it forward, don't stack two lower days." },
    { h: "Why rotate A / B / C / D", p: "A & C hit upper (push/pull/build). B & D hit lower (cuts, jumps, sprint). Mixing <b>strength days</b> (heavy, low reps) with <b>power/hypertrophy days</b> (fast or medium) keeps the nervous system sharp for game day." },
    { h: "Why jumps & sprints count as work", p: "Vertical and first-step speed come from force produced <b>fast</b>, not just heavy. Box jumps, broad jumps, and 5-10-5s are the actual sport — treat them like a lift." },
  ],
  phases: [
    { wk: "1–4",  name: "Foundation",  reps: "5×5 / 3×10", load: "Light → moderate",     focus: "Lock in form. Add weight only when every rep looks clean.", sets: "Sets feel easy at first — that's intentional." },
    { wk: "5–8",  name: "Build",       reps: "4×5 / 4×8",  load: "Push each session",    focus: "Top of rep range hit? Add weight next time. Miss it? Repeat.", sets: "First real pushing phase. PRs start landing here." },
    { wk: "9–11", name: "Peak",        reps: "4×3 / 3×6",  load: "Heavy, slower tempo",  focus: "Max strength + power. Longer rest (2–3 min on big lifts).",  sets: "You'll feel strong. You'll feel fast. This is the payoff." },
    { wk: "12",   name: "Deload",      reps: "3×5 @ 60%",  load: "Back off",             focus: "Half the weight, half the sets. Let the body catch up.",     sets: "Don't skip this. It's what makes the next 12 weeks work." },
  ],
  rules: [
    { h: "Log every set", p: "If it isn't written down it didn't happen. The app tracks it — use it." },
    { h: "Warm up, every time", p: "5 min easy row/bike, then 2 ramp-up sets on your first big lift. Non-negotiable." },
    { h: "Form > weight", p: "One ugly rep wipes out a good set. If a spotter would frown, drop the weight." },
    { h: "Sleep 9+ hrs", p: "You're 14. Growth + strength happen at night. Non-negotiable." },
    { h: "Eat to grow", p: "At 100 lb you need 100+ g protein a day and real meals. Weight room work without food = nothing." },
    { h: "Injury = stop", p: "Sharp pain, anything that changes your form — stop. Tell a parent/coach. Come back when it's gone, not before." },
  ],
  allowance: {
    h: "The allowance rule",
    p: "Hit <b>4 workouts in any rolling 8-day window</b> → allowance earned. Miss the window, the count resets. This keeps you consistent without punishing one bad week. Your progress bar on Today tracks it."
  },
};
